
-- Create Table Student Requests
CREATE TABLE STUDENT_REQUESTS(
	Req_ID VARCHAR2(10),
	Stu_ID VARCHAR2(15) CONSTRAINT STU_ID_FK REFERENCES (STU_ID),
	COURSE_ID NUMBER(7) CONSTRAINT COURSE_ID_FK REFERENCES (COURSE_ID),
	COMMENTS VARCHAR2(200));